### ISSUE TITLE
Install directions broken for Debian jessie

### ISSUE THREAD

**Issue by bnewbold** [zulip/zulip-desktop-legacy#46]
I followed the directions at https://zulip.com/apps/ (Linux tab) on my Debian Jessie (amd64) system, but when I `apt update` I get:

```
W: Failed to fetch http://apt.zulip.com/user/dists/jessie/main/binary-amd64/Packages  404  Not Found
W: Failed to fetch http://apt.zulip.com/user/dists/jessie/main/binary-i386/Packages  404  Not Found
```

I'm not sure if the directions are even supposed to work (in which case they should be removed), or if jessie isn't supported, or what. I couldn't find further directions so I ended up here.

I see there is an issue #1 to set up a PPA on launchpad.net, but over there it looks like there is only a single out-of-date Ubuntu Precise package.

**Comment by bnewbold** [comment]
It looks like the packages just aren't built for jessie; `wheezy` and `precise` work.

**Comment by bnewbold** [comment]
Installing the wheezy package on jessie seems to work for me. I did this by rewriting the `source.list` entry then the usual `apt update && apt install zulip-desktop`.

It would be nice to have either a build for jessie or some indication on the install page that the wheezy package works under jessie, so i'm not closing this issue yet.

Also, cross-referencing a mailing list post which implies that there may be a new Electron-based desktop client app in the pipeline:
https://groups.google.com/forum/#!searchin/zulip-devel/desktop$20electron/zulip-devel/IgQ9B5cEryE/1OJcKwIQCAAJ

**Comment by bnewbold** [comment]
The current install directions (https://zulipchat.com/help/desktop-app-install-guide#linux) worked today on debian stretch (stable).

**Comment by timabbott** [comment]
The current app is an entirely different project; I'm going to disable issues on this legacy project, since it's no longer under development.
