### ISSUE TITLE
On CTRL-R, the server switches.

### ISSUE THREAD

**Issue by brockwhittaker** [zulip/zulip-desktop-legacy#55]
When I'm trying to run my dev server, and I get a screen like this and want to CTRL-R to refresh it, it switches to my other open Zulip server.

![screen shot 2017-10-04 at 11 55 02 am](https://user-images.githubusercontent.com/10321399/31194110-feb7a36e-a8fa-11e7-9e7a-c3f2d8a66c48.png)

**Comment by akashnimare** [comment]
@brockwhittaker Wrong repo? Here - github.com/zulip/zulip-electron/

**Comment by timabbott** [comment]
Just renamed this repo to zulip-desktop-legacy.  We might want to rename the other one to zulip-desktop as well.
